[package]
name = "slate-node"
description = "Binding N-API oficial da Slate para Node.js."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
readme = "../../README.md"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi.workspace = true
napi-derive.workspace = true
slate-core = { path = "../slate-core", version = "2.0.0" }
slate-effects = { path = "../slate-effects", version = "2.0.0" }
slate-input = { path = "../slate-input", version = "2.0.0" }
slate-renderer = { path = "../slate-renderer", version = "2.0.0" }
unicode-width.workspace = true

[build-dependencies]
napi-build.workspace = true
